---
version: "2.1"
services:
  wireguard:
    image: aptupdate/wireguard-dashboard
    container_name: wireguard-dashboard
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
    volumes:
      - /etc/wireguard:/etc/wireguard
      - /lib/modules:/lib/modules
    ports:
      - 10086:10086/tcp
    restart: unless-stopped
